language: node_js
node_js:
  - "12"
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS awesomeG default character set utf8mb4 collate
    utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - npm install mocha -g
before_script:
  - sequelize db:migrate
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: young-hollows-22995
  on:
    repo: harry811016/AwesomeG
