language: node_js
node_js:
  - "10"
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS awesomeG default character set utf8mb4 collate
    utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - npm install mocha -g
before_script:
  - sequelize db:migrate
deploy:
  provider: heroku
  api_key:
    secure: Osyvtr56wynTv6P7q3ocffvoDY1/f8UDbl3EiRyLYYbVZKt1QkW2wexNGJ4KigHBvfIZZQtALuU/06u5PTiTW4cW3gOItFUz6bNuuRX1wDJuPdk54vrhPDxbJoA8aDx3qdwT6iipt8mq7GPC3B7eD/T0zOAklhGFmJGQ0sQE0hs0NW//EKVfLK7AqHv/gslxrDFaaikjeAP3iqmx9OrAz1uvRC5Hsu6dJ5FyuvrxT3RZkzjaddqno4vqOrnc9cgF7pu9zUET//0MbV37umKVEhLZI9l8U83e4s4yrGQRjkUsPOieDqQX6s+5t45wD6W9+bMctk6A6pD21zcm1DCxhkL5xW3n9UosMIPDRB1UUG9NpmzD0f0Gw1ZgsKmFIB5ZIRR9DCTxewYC3kWIpcSCDFo3p9uKi5YSmxatgn9NwyseK8iT18GPmsIfEx4axgEUHYOJ1ba3ElzER0QB0wWQC10VK0fYtFpCC7Jxe6F+k7wwYSzdsLX+bnlpfRDDdA832ksbhbaiFJHix46PLm1HHdUfkpECBlx6UyPgflZvtCifObWcubuaFzZPjf/tEhoJSR9aBRHHuGJ8q6in1EZCEk60Utk1qqjfFIazzDj0Fx6yE+XIUlgocHpv5zAadevIE+f9FehJm+9XP8Cwrv9A0SqOVPG+WTLBtFmuTUoU2bI=
  app: young-hollows-22995
  on:
    repo: harry811016/AwesomeG
