language: node_js
node_js:
  - "12"
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS awesomeG default character set utf8mb4 collate
    utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - npm install mocha -g
before_script:
  - sequelize db:migrate
deploy:
  provider: heroku
  api_key:
    secure: dqd4NHRQ0p0l+JnnAP4/avXRijr263c3OfJZ/my8n5cBvukGJExUd5YVvWKA4p8CkoRUVmPrd6EOhCgkUjEtOOrmh0EqVyk5aPOzAKCOcc5/Pu0HeaUtCsLchLm26IDyeZMJMTnp1nr9wzDYl2YYqQq4gQewd2dwdjapigt1rB7M0yZop6DxYImVq06PGi+4EnNc9f6QF7Q6xpzKMOGowAEO9uxd6RDdVLZeaanUT2I/0yjQAqylQ6ElvqumuRgJidO70Hb6tpsBzyPP+J6zP13JYg/i+eOLz89ZnRzm6n+Xd3nC40AZx2Fmy8wq8LYLpJBdAAH4zew+IoL7oKtbq3mfTLcGphBlR8Huj0sRefAxzKEdkQL0qeGsRT/MeXu7aPkH/Sk2tbzM5cZ+VZA/i7wiwYO/5MOuh+VoWb8WG+/0Nqa+ZbvSybng/+phv9yKyBkEbREawEKS+7uHkETrZfv1b2yYk0tUSuJwXO/vlLNKUYkDAO/A+a/SYCj5zxJ5cY2/xE+uhfONMDjijsbe23y6MjAVGXA31l0GoLYWtuVrPmLsNYNKDCDVhXKIRK1hN9PMNXKLvygosGgcYDUqoZSW8H11vVF4uBx61RReTx7+4oNH3VU/hV8RNjdA0mwFt0VcrspLEgebGeZUE9/sT6tMznvagbAjIomlfd6/qTw=
  app: young-hollows-22995
  on:
    repo: harry811016/AwesomeG
