language: node_js
node_js:
  - "10"
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS awesomeG default character set utf8mb4 collate
    utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - npm install mocha -g
before_script:
  - sequelize db:migrate
deploy:
  provider: heroku
  api_key:
    secure: PMNvzVAP2Nd09HJNI8p1h2mY9/NsXrZIRo40UflqZuW7XKB2eNEMrkQtqXoLcqTf4T2qsNaned0h4xBvkhf7s70jORExr0Ah2CbQUvsxBrfNtjyijS2XFJRrFR65asiiUaJDAjgHk6VwBmwENYyru6yM1XDmyXd8A1ExqhtbSJHcTwYiZMrh1T7DvPPP5bGn34rkCQZagTm6BfAKZXYrFS9jx6hYNce5+Q+y3LPDAV7EX+rS2c1gTEv3RrnDHmpoeL6XLs4SckToh1GL3HJ0O1Orun/2Qmt7RRIL+SWba350PtWgEwiPS6MT8gEk4Di4w0MkOkeal0z4hlI4In0Z4GAIsbXC/DgMVYlcmIQWKr32VOwCK2GsaLIgb202T5rB3l8pwM3s5+Hbq6Vguud+fNkZbrH8KvPTqxboh+/olet7yyAkSAZuB4j6Kj4IKFfkAAZVdoB2RlNfaRWSxBZ3S4grsj5pEs91udv0pDVM2ly7zY7OEBYPBLW4QVvneI2ZquzkwftAx1prAlZGQDvHmqzjU/V9x4L0NLyWRwiFcmM1UJS76c4Ezhv+TPz3q9zAIQh32snde0upZFyzK6OLawv8CpQnruNVKM9miOEKcgDJKDnPLL4EzTuG1Ur94xBBdrX5Ep/MC6S2r05CvNLdTtolGLP8xaF+ANEM1wbEtXE=
  app: young-hollows-22995
  on:
    repo: harry811016/AwesomeG
